# Generated by Django 5.0.2 on 2024-02-10 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=24)),
                ('lname', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=64)),
                ('pfPhoto', models.ImageField(upload_to='images')),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
