# Generated by Django 5.0.2 on 2024-02-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_eusers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='eusers',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
