# Generated by Django 5.0.2 on 2024-02-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_eusers_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('rating', models.FloatField()),
                ('ratingStrength', models.IntegerField()),
            ],
        ),
    ]
